version: "3.9"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  app:
    build:
      context: ./
    command: npm run start
    env_file:
      - .env.local
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbitmq
    environment:
      - BLOCKBOOK_API_URL=https://blockbook.syscoin.org
      - DATABASE_URL=postgresql://admin:admin@db:5432/mydb?schema=public

  transaction-monitor:
    build:
      context: ./oracles
      dockerfile: Dockerfile
    command: npm run start-transaction-monitor

    volumes:
      - ./oracles/transaction-monitor-oracle.ts:/app/transaction-monitor-oracle.ts
    depends_on:
      - rabbitmq
      - app
    environment:
      - API_URL=http://app:3000/api
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - BLOCKBOOK_API_URL=https://blockbook.syscoin.org/api

  transaction-registration:
    build:
      context: ./oracles
      dockerfile: Dockerfile
    command: npm run start-transaction-registration
    volumes:
      - ./oracles/transaction-registration.ts:/app/transaction-registration.ts
    depends_on:
      - rabbitmq
      - app
    env_file:
      - ./oracles/.env.docker.transaction-registration
    environment:
      - API_URL=http://app:3000/api
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - BLOCKBOOK_API_URL=https://blockbook.syscoin.org/api
      - DATABASE_URL=postgresql://admin:admin@db:5432/transactions?schema=public
      - RPC_URL=http://localhost:8545
