version: "3.9"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  rpc:
    build:
      context: ./contract
      dockerfile: Dockerfile
    ports:
      - 8545:8545

  app:
    build:
      context: ./
    volumes:
      - ./contract/artifacts/contracts/FundDistributor.sol/FundDistributor.json:/app/abi.json
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbitmq
      # - rpc
    environment:
      - BLOCKBOOK_API_URL=https://blockbook.syscoin.org
      - DATABASE_URL=postgresql://admin:admin@db:5432/bridge?schema=public
      - RPC_URL=http://rpc:8545
      - FUND_DISTRIBUTOR_ABI_FILE_PATH=/app/abi.json

  transaction-monitor:
    build:
      context: ./oracles
      dockerfile: Dockerfile
    command: npm run start-transaction-monitor
    env_file:
      - ./oracles/.env.docker.transaction-registration
    volumes:
      - ./oracles/transaction-monitor-oracle.ts:/app/transaction-monitor-oracle.ts
      - ./contract/artifacts/contracts/FundDistributor.sol/FundDistributor.json:/app/abi.json
    depends_on:
      - rabbitmq
      - rpc
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - BLOCKBOOK_API_URL=https://blockbook.syscoin.org/api
      - RPC_URL=http://rpc:8545
      - FUND_DISTRIBUTOR_ABI_FILE_PATH=/app/abi.json

  transaction-registration:
    build:
      context: ./oracles
      dockerfile: Dockerfile
    command: npm run start-transaction-registration
    volumes:
      - ./oracles/transaction-registration.ts:/app/transaction-registration.ts
      - ./contract/artifacts/contracts/FundDistributor.sol/FundDistributor.json:/app/abi.json
    depends_on:
      - rabbitmq
      - rpc
    env_file:
      - ./oracles/.env.docker.transaction-registration
    environment:
      - BRIDGE_API_URL=http://app:3000/api
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - BLOCKBOOK_API_URL=https://blockbook.syscoin.org/api
      - DATABASE_URL=postgresql://admin:admin@db:5432/transactions?schema=public
      - RPC_URL=http://rpc:8545b
      - FUND_DISTRIBUTOR_ABI_FILE_PATH=/app/abi.json

  transaction-payout:
    build:
      context: ./oracles
      dockerfile: Dockerfile
    command: npm run start-transaction-payout
    volumes:
      - ./oracles/payout-oracle.ts:/app/payout-oracle.ts
      - ./contract/artifacts/contracts/FundDistributor.sol/FundDistributor.json:/app/abi.json
    depends_on:
      - rabbitmq
      - rpc
    env_file:
      - ./oracles/.env.docker.payout
    environment:
      - BRIDGE_API_URL=http://app:3000/api
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - BLOCKBOOK_API_URL=https://blockbook.syscoin.org/api
      - DATABASE_URL=postgresql://admin:admin@db:5432/transactions?schema=public
      - RPC_URL=http://rpc:8545
      - FUND_DISTRIBUTOR_ABI_FILE_PATH=/app/abi.json
